<a href="https://colab.research.google.com/github/Priyadarshini-yadav13/Rashmi/blob/main/LSTM_truly_interesting__project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
Data="""Melissa sneaked behind the teacher as he wrote an equation on the board.
She sat on her seat, trying hard not to make a noise.
The teacher turned around to explain what he had written on the board.
He turned around and looked confused. “Melissa, I didn’t see you.
Were you not there in the morning?” asked teacher.
I honestly think you need new glasses at this point”, joked Melissa.
The whole room started to laugh.Teacher ignored it and got back to teaching.
Melissa was relieved she didn’t get caught sneaking in.
She did not want anyone knowing the reason she was late.
She partied all night long with her friend Meleena who was absent that day, came home at 3 and slept really late.
She barely had enough time to eat her breakfast in the morning as she woke up so late.
Meleena was her best friend and helped her with all her problems, Melissa missed her at school.
The day went by with boring classes and high school drama Melissa did not want to be a part of.
She went home and cooked some lasagna.
She cooked for herself as her parents weren’t home.
They had gone to Paris for celebrating their 20th anniversary.
They refused to take Melissa, because they thought she would ruin their vacation. Melissa wasn’t mad at them, she agreed.
After finishing her lasagna, she took a warm shower, meditated, took her medication and went to sleep.
Her alarm ringed when it was 4 in the morning.
She woke up with her brain barely functioning and her body aching.
First, she drank a warm glass of water.
Then, she took a shower, brushed her teeth, washed her face and wore comfortable clothing."""

In [ ]:
tokenizer.word_index

{'she': 1,
 'her': 2,
 'the': 3,
 'to': 4,
 'and': 5,
 'melissa': 6,
 'a': 7,
 'was': 8,
 'teacher': 9,
 'not': 10,
 'in': 11,
 'at': 12,
 'with': 13,
 'as': 14,
 'he': 15,
 'on': 16,
 'had': 17,
 'you': 18,
 'morning': 19,
 'late': 20,
 'home': 21,
 'went': 22,
 'they': 23,
 'took': 24,
 'board': 25,
 'turned': 26,
 'around': 27,
 'i': 28,
 'didn’t': 29,
 'it': 30,
 'did': 31,
 'want': 32,
 'all': 33,
 'friend': 34,
 'meleena': 35,
 'day': 36,
 'barely': 37,
 'woke': 38,
 'up': 39,
 'school': 40,
 'of': 41,
 'cooked': 42,
 'lasagna': 43,
 'for': 44,
 'their': 45,
 'warm': 46,
 'shower': 47,
 'sneaked': 48,
 'behind': 49,
 'wrote': 50,
 'an': 51,
 'equation': 52,
 'sat': 53,
 'seat': 54,
 'trying': 55,
 'hard': 56,
 'make': 57,
 'noise': 58,
 'explain': 59,
 'what': 60,
 'written': 61,
 'looked': 62,
 'confused': 63,
 '“melissa': 64,
 'see': 65,
 'were': 66,
 'there': 67,
 '”': 68,
 'asked': 69,
 'honestly': 70,
 'think': 71,
 'need': 72,
 'new': 73,
 'glasses': 74,
 'this': 75,
 'poin

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer=Tokenizer()

In [ ]:
tokenizer.fit_on_texts([Data])

In [ ]:
for sentence in Data.split('.'):
    print(sentence)

Melissa sneaked behind the teacher as he wrote an equation on the board

She sat on her seat, trying hard not to make a noise

The teacher turned around to explain what he had written on the board
 
He turned around and looked confused
 “Melissa, I didn’t see you
 
Were you not there in the morning?” asked teacher

I honestly think you need new glasses at this point”, joked Melissa

The whole room started to laugh
Teacher ignored it and got back to teaching
 
Melissa was relieved she didn’t get caught sneaking in

She did not want anyone knowing the reason she was late

She partied all night long with her friend Meleena who was absent that day, came home at 3 and slept really late

She barely had enough time to eat her breakfast in the morning as she woke up so late

Meleena was her best friend and helped her with all her problems, Melissa missed her at school
 
The day went by with boring classes and high school drama Melissa did not want to be a part of
 
She went home and cooked som

In [ ]:
print(tokenizer.texts_to_sequences([Data]))

[[6, 48, 49, 3, 9, 14, 15, 50, 51, 52, 16, 3, 25, 1, 53, 16, 2, 54, 55, 56, 10, 4, 57, 7, 58, 3, 9, 26, 27, 4, 59, 60, 15, 17, 61, 16, 3, 25, 15, 26, 27, 5, 62, 63, 64, 28, 29, 65, 18, 66, 18, 10, 67, 11, 3, 19, 68, 69, 9, 28, 70, 71, 18, 72, 73, 74, 12, 75, 76, 77, 6, 3, 78, 79, 80, 4, 81, 9, 82, 30, 5, 83, 84, 4, 85, 6, 8, 86, 1, 29, 87, 88, 89, 11, 1, 31, 10, 32, 90, 91, 3, 92, 1, 8, 20, 1, 93, 33, 94, 95, 13, 2, 34, 35, 96, 8, 97, 98, 36, 99, 21, 12, 100, 5, 101, 102, 20, 1, 37, 17, 103, 104, 4, 105, 2, 106, 11, 3, 19, 14, 1, 38, 39, 107, 20, 35, 8, 2, 108, 34, 5, 109, 2, 13, 33, 2, 110, 6, 111, 2, 12, 40, 3, 36, 22, 112, 13, 113, 114, 5, 115, 40, 116, 6, 31, 10, 32, 4, 117, 7, 118, 41, 1, 22, 21, 5, 42, 119, 43, 1, 42, 44, 120, 14, 2, 121, 122, 21, 23, 17, 123, 4, 124, 44, 125, 45, 126, 127, 23, 128, 4, 129, 6, 130, 23, 131, 1, 132, 133, 45, 134, 6, 135, 136, 12, 137, 1, 138, 139, 140, 2, 43, 1, 24, 7, 46, 47, 141, 24, 2, 142, 5, 22, 4, 143, 2, 144, 145, 146, 30, 8, 147, 11, 3, 19

In [ ]:
for sentence in Data.split('.'):
    print(tokenizer.texts_to_sequences([sentence])[0])

[6, 48, 49, 3, 9, 14, 15, 50, 51, 52, 16, 3, 25]
[1, 53, 16, 2, 54, 55, 56, 10, 4, 57, 7, 58]
[3, 9, 26, 27, 4, 59, 60, 15, 17, 61, 16, 3, 25]
[15, 26, 27, 5, 62, 63]
[64, 28, 29, 65, 18]
[66, 18, 10, 67, 11, 3, 19, 68, 69, 9]
[28, 70, 71, 18, 72, 73, 74, 12, 75, 76, 77, 6]
[3, 78, 79, 80, 4, 81]
[9, 82, 30, 5, 83, 84, 4, 85]
[6, 8, 86, 1, 29, 87, 88, 89, 11]
[1, 31, 10, 32, 90, 91, 3, 92, 1, 8, 20]
[1, 93, 33, 94, 95, 13, 2, 34, 35, 96, 8, 97, 98, 36, 99, 21, 12, 100, 5, 101, 102, 20]
[1, 37, 17, 103, 104, 4, 105, 2, 106, 11, 3, 19, 14, 1, 38, 39, 107, 20]
[35, 8, 2, 108, 34, 5, 109, 2, 13, 33, 2, 110, 6, 111, 2, 12, 40]
[3, 36, 22, 112, 13, 113, 114, 5, 115, 40, 116, 6, 31, 10, 32, 4, 117, 7, 118, 41]
[1, 22, 21, 5, 42, 119, 43]
[1, 42, 44, 120, 14, 2, 121, 122, 21]
[23, 17, 123, 4, 124, 44, 125, 45, 126, 127]
[23, 128, 4, 129, 6, 130, 23, 131, 1, 132, 133, 45, 134]
[6, 135, 136, 12, 137, 1, 138]
[139, 140, 2, 43, 1, 24, 7, 46, 47, 141, 24, 2, 142, 5, 22, 4, 143]
[2, 144, 145, 146, 3

In [ ]:
input_sequences=[]
for sentence in Data.split('.'):
  tokenized_sentence=tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [ ]:
input_sequences

[[6, 48],
 [6, 48, 49],
 [6, 48, 49, 3],
 [6, 48, 49, 3, 9],
 [6, 48, 49, 3, 9, 14],
 [6, 48, 49, 3, 9, 14, 15],
 [6, 48, 49, 3, 9, 14, 15, 50],
 [6, 48, 49, 3, 9, 14, 15, 50, 51],
 [6, 48, 49, 3, 9, 14, 15, 50, 51, 52],
 [6, 48, 49, 3, 9, 14, 15, 50, 51, 52, 16],
 [6, 48, 49, 3, 9, 14, 15, 50, 51, 52, 16, 3],
 [6, 48, 49, 3, 9, 14, 15, 50, 51, 52, 16, 3, 25],
 [1, 53],
 [1, 53, 16],
 [1, 53, 16, 2],
 [1, 53, 16, 2, 54],
 [1, 53, 16, 2, 54, 55],
 [1, 53, 16, 2, 54, 55, 56],
 [1, 53, 16, 2, 54, 55, 56, 10],
 [1, 53, 16, 2, 54, 55, 56, 10, 4],
 [1, 53, 16, 2, 54, 55, 56, 10, 4, 57],
 [1, 53, 16, 2, 54, 55, 56, 10, 4, 57, 7],
 [1, 53, 16, 2, 54, 55, 56, 10, 4, 57, 7, 58],
 [3, 9],
 [3, 9, 26],
 [3, 9, 26, 27],
 [3, 9, 26, 27, 4],
 [3, 9, 26, 27, 4, 59],
 [3, 9, 26, 27, 4, 59, 60],
 [3, 9, 26, 27, 4, 59, 60, 15],
 [3, 9, 26, 27, 4, 59, 60, 15, 17],
 [3, 9, 26, 27, 4, 59, 60, 15, 17, 61],
 [3, 9, 26, 27, 4, 59, 60, 15, 17, 61, 16],
 [3, 9, 26, 27, 4, 59, 60, 15, 17, 61, 16, 3],
 [3, 9, 26, 

In [ ]:
max_len=max([len(x) for x in input_sequences])

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences=pad_sequences(input_sequences,maxlen=max_len,padding='pre')

In [ ]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,   6,  48],
       [  0,   0,   0, ...,   6,  48,  49],
       [  0,   0,   0, ...,  48,  49,   3],
       ...,
       [  0,   0,   0, ..., 160,   5, 161],
       [  0,   0,   0, ...,   5, 161, 162],
       [  0,   0,   0, ..., 161, 162, 163]], dtype=int32)

In [ ]:
X=padded_input_sequences[:,:-1]

In [ ]:
y=padded_input_sequences[:,-1]

In [ ]:
X

array([[  0,   0,   0, ...,   0,   0,   6],
       [  0,   0,   0, ...,   0,   6,  48],
       [  0,   0,   0, ...,   6,  48,  49],
       ...,
       [  0,   0,   0, ...,   2, 160,   5],
       [  0,   0,   0, ..., 160,   5, 161],
       [  0,   0,   0, ...,   5, 161, 162]], dtype=int32)

In [ ]:
y

array([ 48,  49,   3,   9,  14,  15,  50,  51,  52,  16,   3,  25,  53,
        16,   2,  54,  55,  56,  10,   4,  57,   7,  58,   9,  26,  27,
         4,  59,  60,  15,  17,  61,  16,   3,  25,  26,  27,   5,  62,
        63,  28,  29,  65,  18,  18,  10,  67,  11,   3,  19,  68,  69,
         9,  70,  71,  18,  72,  73,  74,  12,  75,  76,  77,   6,  78,
        79,  80,   4,  81,  82,  30,   5,  83,  84,   4,  85,   8,  86,
         1,  29,  87,  88,  89,  11,  31,  10,  32,  90,  91,   3,  92,
         1,   8,  20,  93,  33,  94,  95,  13,   2,  34,  35,  96,   8,
        97,  98,  36,  99,  21,  12, 100,   5, 101, 102,  20,  37,  17,
       103, 104,   4, 105,   2, 106,  11,   3,  19,  14,   1,  38,  39,
       107,  20,   8,   2, 108,  34,   5, 109,   2,  13,  33,   2, 110,
         6, 111,   2,  12,  40,  36,  22, 112,  13, 113, 114,   5, 115,
        40, 116,   6,  31,  10,  32,   4, 117,   7, 118,  41,  22,  21,
         5,  42, 119,  43,  42,  44, 120,  14,   2, 121, 122,  2

In [ ]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=len(tokenizer.word_index)+1)

In [ ]:
y.shape

(265, 164)

In [ ]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [ ]:
model=Sequential()
model.add(Embedding(len(tokenizer.word_index)+1,100,input_length=max_len-1))
model.add(LSTM(150))
model.add(Dense(len(tokenizer.word_index)+1,activation='softmax'))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Explicitly build the model with the input shape of X to force parameter initialization
model.build(input_shape=(None, X.shape[1]))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 21, 100)        │        16,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 164)            │        24,764 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 191,764 (749.08 KB)

 Trainable params: 191,764 (749.08 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X,y,epochs=100)

Epoch 1/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 3s 73ms/step - accuracy: 0.0226 - loss: 5.0981
Epoch 2/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 70ms/step - accuracy: 0.0491 - loss: 5.0386
Epoch 3/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.0528 - loss: 4.8958
Epoch 4/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.0528 - loss: 4.8122
Epoch 5/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.0491 - loss: 4.7864
Epoch 6/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.0491 - loss: 4.7493
Epoch 7/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.0528 - loss: 4.7023
Epoch 8/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.0528 - loss: 4.6581
Epoch 9/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.0566 - loss: 4.6128
Epoch 10/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.0642 - loss: 4.5389
Epoch 11/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.0642 - loss: 4.4788
Epoch 12/100
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.0566 - lo

In [ ]:
text="melissa"
#tokenize
token_text=tokenizer.texts_to_sequences([text])[0]
##padding
padded_token_text=pad_sequences([token_text],maxlen=max_len-1,padding='pre')
print(padded_token_text)
##predict
pos=np.argmax(model.predict(padded_token_text))
for word,index in tokenizer.word_index.items():
  if index==pos:
    print(word)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 6]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
sneaked


In [ ]:
## for 12 words predictions
text="melissa"
for i in range(12):
  #tokenize
  token_text=tokenizer.texts_to_sequences([text])[0]
  ##padding
  padded_token_text=pad_sequences([token_text],maxlen=max_len-1,padding='pre')
  print(padded_token_text)
  ##predict
  pos=np.argmax(model.predict(padded_token_text, verbose=0))
  for word,index in tokenizer.word_index.items():
    if index==pos:
      text=text+" "+word
      print(text)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 6]]
melissa sneaked
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  6 48]]
melissa sneaked behind
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  6 48 49]]
melissa sneaked behind the
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  6 48 49  3]]
melissa sneaked behind the teacher
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  6 48 49  3  9]]
melissa sneaked behind the teacher as
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  6 48 49  3  9 14]]
melissa sneaked behind the teacher as he
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  6 48 49  3  9 14 15]]
melissa sneaked behind the teacher as he wrote
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  6 48 49  3  9 14 15 50]]
melissa sneaked behind the teacher as he wrote an
[[ 0  0  0  0  0  0  0  0  0  0  0  0  6 48 49  3  9 14 15 50 51]]
melissa sneaked behind the teacher as he wrote an equation
[[ 0  0  0  0  0  0  0  0  0  0  0  6 48 49  3  9 14 15 50 51 52]]
melissa sneaked

In [ ]:
## for 12 words predictions
import time
text="melissa"
for i in range(12):
  #tokenize
  token_text=tokenizer.texts_to_sequences([text])[0]
  ##padding
  padded_token_text=pad_sequences([token_text],maxlen=max_len-1,padding='pre')
  print(padded_token_text)
  ##predict
  pos=np.argmax(model.predict(padded_token_text, verbose=0))
  for word,index in tokenizer.word_index.items():
    if index==pos:
      text=text+" "+word
      print(text)
      time.sleep(2)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 6]]
melissa sneaked
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  6 48]]
melissa sneaked behind
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  6 48 49]]
melissa sneaked behind the
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  6 48 49  3]]
melissa sneaked behind the teacher
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  6 48 49  3  9]]
melissa sneaked behind the teacher as
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  6 48 49  3  9 14]]
melissa sneaked behind the teacher as he
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  6 48 49  3  9 14 15]]
melissa sneaked behind the teacher as he wrote
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  6 48 49  3  9 14 15 50]]
melissa sneaked behind the teacher as he wrote an
[[ 0  0  0  0  0  0  0  0  0  0  0  0  6 48 49  3  9 14 15 50 51]]
melissa sneaked behind the teacher as he wrote an equation
[[ 0  0  0  0  0  0  0  0  0  0  0  6 48 49  3  9 14 15 50 51 52]]
melissa sneaked

In [ ]:
## for 12 words predictions
import time
text="teacher"
for i in range(12):
  #tokenize
  token_text=tokenizer.texts_to_sequences([text])[0]
  ##padding
  padded_token_text=pad_sequences([token_text],maxlen=max_len-1,padding='pre')
  print(padded_token_text)
  ##predict
  pos=np.argmax(model.predict(padded_token_text, verbose=0))
  for word,index in tokenizer.word_index.items():
    if index==pos:
      text=text+" "+word
      print(text)
      time.sleep(2)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 9]]
teacher ignored
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  9 82]]
teacher ignored it
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  9 82 30]]
teacher ignored it and
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  9 82 30  5]]
teacher ignored it and got
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  9 82 30  5 83]]
teacher ignored it and got back
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  9 82 30  5 83 84]]
teacher ignored it and got back to
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  9 82 30  5 83 84  4]]
teacher ignored it and got back to teaching
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  9 82 30  5 83 84  4 85]]
teacher ignored it and got back to teaching teaching
[[ 0  0  0  0  0  0  0  0  0  0  0  0  9 82 30  5 83 84  4 85 85]]
teacher ignored it and got back to teaching teaching teaching
[[ 0  0  0  0  0  0  0  0  0  0  0  9 82 30  5 83 84  4 85 85 85]]
teacher ignored it and got back to teach